/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;  
/**
 *
 * @author En Tay
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        
        getContentPane().setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageBg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileMaster = new javax.swing.JMenu();
        menuFileMasterBarang = new javax.swing.JMenuItem();
        menuFileExit = new javax.swing.JMenuItem();
        menuUtility = new javax.swing.JMenu();
        menuUtilityJamPublic = new javax.swing.JMenuItem();
        menuUtilityJamPrivate = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        imageBg.setBackground(new java.awt.Color(255, 255, 255));
        imageBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/logo.png"))); // NOI18N

        menuFile.setMnemonic('f');
        menuFile.setText("File");

        menuFileMaster.setText("Master");

        menuFileMasterBarang.setText("Barang");
        menuFileMasterBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileMasterBarangActionPerformed(evt);
            }
        });
        menuFileMaster.add(menuFileMasterBarang);

        menuFile.add(menuFileMaster);

        menuFileExit.setMnemonic('x');
        menuFileExit.setText("Exit");
        menuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileExitActionPerformed(evt);
            }
        });
        menuFile.add(menuFileExit);

        jMenuBar1.add(menuFile);

        menuUtility.setText("Utility");

        menuUtilityJamPublic.setText("Jam (Public)");
        menuUtilityJamPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilityJamPublicActionPerformed(evt);
            }
        });
        menuUtility.add(menuUtilityJamPublic);

        menuUtilityJamPrivate.setText("Jam (Private)");
        menuUtilityJamPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtilityJamPrivateActionPerformed(evt);
            }
        });
        menuUtility.add(menuUtilityJamPrivate);

        jMenuBar1.add(menuUtility);

        menuHelp.setText("Help");

        menuAbout.setMnemonic('a');
        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imageBg)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imageBg)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuFileExitActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Dibuat oleh\nEnTay");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuFileMasterBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileMasterBarangActionPerformed
        new MasterBarang().setVisible(true);
    }//GEN-LAST:event_menuFileMasterBarangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void menuUtilityJamPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilityJamPublicActionPerformed
        FormJamPublic f = new FormJamPublic();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMM yyyy");  
        LocalDateTime now = LocalDateTime.now();  
        f.labelHari.setText(dtf.format(now));
        f.labelSalam.setText("Halo, "+Global.NAMA);
        f.setVisible(true);
    }//GEN-LAST:event_menuUtilityJamPublicActionPerformed

    private void menuUtilityJamPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtilityJamPrivateActionPerformed
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMM yyyy");  
        LocalDateTime now = LocalDateTime.now();  
        new FormJamPrivate().tampilkan(dtf.format(now));
    }//GEN-LAST:event_menuUtilityJamPrivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBg;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileExit;
    private javax.swing.JMenu menuFileMaster;
    private javax.swing.JMenuItem menuFileMasterBarang;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuUtility;
    private javax.swing.JMenuItem menuUtilityJamPrivate;
    private javax.swing.JMenuItem menuUtilityJamPublic;
    // End of variables declaration//GEN-END:variables
}
